services:
  - name: db
    env: 'docker'
    region: singapore
    plan: free
    dockerFile: Dockerfile
    healthCheckPath: /
    rootDir: backend/app
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password

  - name: backend
    env: 'docker'
    dockerFile: Dockerfile
    dockerContext: backend
    envVars:
      - key: RAILS_ENV
        value: production
    startCommand: 'bundle exec rails s -p 3000 -b 0.0.0.0'
    rootDir: backend/app
    autoDeploy: true
    healthCheckPath: /

  - name: frontend
    env: 'docker'
    dockerFile: Dockerfile
    dockerContext: frontend
    startCommand: 'yarn dev'
    rootDir: frontend/app
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000

databases:
  - name: db
    ipAllowList: []  # Allow internal connections only
